[package]
name = "vxtoolcli"
version = "1.3.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion="*"
tokio="*"
url="*"
reqwest = { version = "0.11", features = ["blocking", "json"] }